version: '3.9'

services:
  login_service:
    build:
      context: ./login_module
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network

  inventario_service:
    build:
      context: ./artesanias-bogota
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - app-network

  pago_service:
    build:
      context: ./pago-module
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
